---
micronaut:
  application:
    name: elastic-client

---
elasticsearch:
  httpHosts: "https://192.168.1.133:30474,https://192.168.1.133:30474"
  request:
    default:
      expectContinueEnabled: true
      localAddress: 192.168.1.133
  host: ${ELASTIC_HOST:192.168.1.133}
  port: ${ELASTIC_PORT:30474}
  connectionTimeout: 5000
  connectionRequestTimeout: 5000
  socketTimeout: 5000
  maxRetryTimeout: 5000
